# Generated by Django 2.1.3 on 2018-11-16 05:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(default=datetime.date(2018, 11, 15))),
                ('site', models.CharField(choices=[('PAC', 'Performing Arts Center'), ('Slavik', 'Slavik'), ('M-S', 'MacKenzie-Scott')], default=None, max_length=24, verbose_name='Site')),
                ('department', models.CharField(choices=[('Music', 'Music'), ('Games', 'Games'), ('Education/Learning', 'Education/Learning'), ('Teen', 'Teen'), ('Athletics/Aquatics', 'Athletics/Aquatics'), ('Art', 'Art'), ('Tech', 'Tech'), ('Other', 'Other')], max_length=24, verbose_name='Department')),
                ('report_complete', models.BooleanField(default=False)),
                ('program', models.CharField(choices=[('Project Learn', 'Project Learn'), ('Power Hour', 'Power Hour'), ('Club Tech', 'Club Tech'), ('College Bound', 'College Bound'), ('Money Matters', 'Money Matters'), ('Career Launch', 'Career Launch'), ('Torch Club', 'Torch Club'), ('Keystone Club', 'Keystone Club'), ('Triple Play', 'Triple Play'), ('SMART Moves', 'SMART Moves'), ('SMART Girls', 'SMART Girls'), ('Passport to Manhood', 'Passport to Manhood'), ('NetSmartz', 'NetSmartz'), ('Image Makers', 'Image Makers'), ('Clay Tech', 'Clay Tech'), ('Drama Matters', 'Drama Matters'), ('Music', 'Music'), ('Aquatics', 'Aquatics'), ('Youth of the Year', 'Youth of the Year'), ('OTHER', 'OTHER')], max_length=48, verbose_name='Program')),
                ('summary', models.TextField(blank=True, max_length=2000)),
                ('feedback_challenges', models.TextField(blank=True, max_length=2000)),
                ('members', models.ManyToManyField(blank=True, related_name='members', to='members.Member')),
                ('report_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Employee')),
            ],
        ),
    ]
